# Generated by Django 5.0.6 on 2024-06-11 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=255)),
                ('codename', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=150, unique=True)),
                ('first_name', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=150)),
                ('last_name', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=150)),
                ('email', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, db_collation='Modern_Spanish_CI_AS', null=True)),
                ('object_repr', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField(db_collation='Modern_Spanish_CI_AS')),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=100)),
                ('model', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=255)),
                ('name', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField(db_collation='Modern_Spanish_CI_AS')),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Paymentmethods',
            fields=[
                ('paymentid', models.AutoField(db_column='PaymentId', primary_key=True, serialize=False)),
                ('paymentdescription', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='PaymentDescription', max_length=100, null=True)),
                ('enabled', models.BooleanField(blank=True, db_column='Enabled', null=True)),
                ('dateadded', models.DateTimeField(blank=True, db_column='DateAdded', null=True)),
            ],
            options={
                'verbose_name_plural': 'Payment methods',
                'db_table': 'PaymentMethods',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('productid', models.AutoField(db_column='ProductId', primary_key=True, serialize=False)),
                ('productname', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='ProductName', max_length=50, null=True)),
                ('productprice', models.FloatField(blank=True, db_column='ProductPrice', null=True)),
            ],
            options={
                'verbose_name_plural': 'Products',
                'db_table': 'Products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('reportid', models.AutoField(db_column='ReportId', primary_key=True, serialize=False)),
                ('reportname', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='ReportName', max_length=100, null=True)),
                ('storedprocedure', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='StoredProcedure', max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Reports',
                'db_table': 'Reports',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('saleid', models.AutoField(db_column='SaleId', primary_key=True, serialize=False)),
                ('totalprice', models.FloatField(blank=True, db_column='TotalPrice', null=True)),
                ('paymentmethodid', models.IntegerField(blank=True, db_column='PaymentMethodId', null=True)),
                ('date', models.DateTimeField(blank=True, db_column='Date', null=True)),
            ],
            options={
                'verbose_name_plural': 'Sales',
                'db_table': 'Sales',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Salesdetails',
            fields=[
                ('saledetailid', models.AutoField(db_column='SaleDetailId', primary_key=True, serialize=False)),
                ('individualprice', models.FloatField(blank=True, db_column='IndividualPrice', null=True)),
                ('amount', models.IntegerField(blank=True, db_column='Amount', null=True)),
            ],
            options={
                'verbose_name_plural': 'Sales details',
                'db_table': 'SalesDetails',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stockhistory',
            fields=[
                ('historyid', models.AutoField(db_column='HistoryId', primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(blank=True, db_column='Quantity', null=True)),
                ('operation', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='Operation', max_length=1, null=True)),
                ('date', models.DateTimeField(blank=True, db_column='Date', null=True)),
            ],
            options={
                'verbose_name_plural': 'Stock history',
                'db_table': 'StockHistory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userid', models.AutoField(db_column='UserId', primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='Username', max_length=30, null=True)),
                ('enabled', models.BooleanField(blank=True, db_column='Enabled', null=True)),
                ('lastlogin', models.DateTimeField(blank=True, db_column='LastLogin', null=True)),
            ],
            options={
                'db_table': 'Users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usersroles',
            fields=[
                ('roleid', models.AutoField(db_column='RoleId', primary_key=True, serialize=False)),
                ('rolename', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='RoleName', max_length=25, null=True)),
            ],
            options={
                'db_table': 'UsersRoles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('productid', models.OneToOneField(db_column='ProductId', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='dashboard.products')),
                ('quantity', models.IntegerField(blank=True, db_column='Quantity', null=True)),
            ],
            options={
                'verbose_name_plural': 'Stock',
                'db_table': 'Stock',
                'managed': False,
            },
        ),
    ]
